services:
  - type: web
    name: iris-backend
    runtime: node
    repo: https://github.com/bsc-s-s/iris-backend
    region: oregon
    plan: free
    branch: main
    buildCommand: cd server && npm install && npx prisma generate && npx nest build
    startCommand: cd server && node dist/main.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: DB_HOST
        value: aws-0-eu-west-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.emhqfkdeeuqgojvjonkg
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 15m
      - key: GROQ_KEY
        sync: false
      - key: SB_URL
        sync: false
      - key: SB_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://iris-frontend-y053.onrender.com
      - key: CORS_ORIGIN
        value: https://iris-frontend-y053.onrender.com
      - key: PAYPAL_CLIENT_ID
        value: "AdgvI-2xswXYx4HtswYSKe37jG99ICylWiZTtpw0S5Gr08-VpjEL-Lra5ES_tV5ZjrU51-8dwrrAxhif"
      - key: PAYPAL_CLIENT_SECRET
        value: "EFxtO7BCCVA0MugPMOSAer2XJVaOeNTVj-CtSBEMnzMg7sTn6-1dEnnYm2eLvLGNNaHCb2BIkJMaPYqL"
      - key: PAYPAL_MODE
        value: live

  - type: web
    name: iris-frontend
    runtime: node
    repo: https://github.com/bsc-s-s/iris-backend
    region: oregon
    plan: free
    branch: main
    buildCommand: cd web && npm install && npm run build
    startCommand: cd web && node .next/standalone/server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NEXT_PUBLIC_API_URL
        value: https://iris-backend-b9fw.onrender.com
