const dict: Record<string, string> = {
  'sidebar.iris': 'IRIS™ Platform',
  'sidebar.legacy': 'Legacy',
  'sidebar.intelligence': 'IRIS Intelligence',
  'sidebar.scan': 'IRIS Scan',
  'sidebar.alerts': 'IRIS Alerts',
  'sidebar.signals': 'Risk Signals',
  'sidebar.monitor': 'IRIS Monitor',
  'sidebar.predict': 'IRIS Predict',
  'sidebar.benchmark': 'Benchmark',
  'sidebar.reports': 'Reports',
  'sidebar.dashboard': 'Dashboard',
  'sidebar.assessments': 'Assessments',
  'sidebar.forecast': 'Risk Forecast',
  'sidebar.compliance': 'Compliance',
  'sidebar.compliance_center': 'Compliance Center',
  'sidebar.gdpr': 'GDPR',
  'sidebar.iso27001': 'ISO 27001',
  'sidebar.privacy': 'Privacy',
  'sidebar.anomalies': 'Anomalies',
  'sidebar.api_keys': 'API Keys',
  'sidebar.webhooks': 'Webhooks',
  'sidebar.planning': 'Security Planning',
  'sidebar.simulation': 'Threat Simulation',
  'sidebar.ai_analyst': 'AI Analyst',
  'sidebar.billing': 'Billing',
  'sidebar.sso': 'SSO',
  'sidebar.users': 'Users',
  'sidebar.audit': 'Audit',
  'sidebar.zero_trust': 'Zero Trust',
  'sidebar.settings': 'Settings',
  'sidebar.logout': 'Logout',
  'sidebar.loading': 'Loading...',
  'sidebar.enterprise_v5': 'Enterprise v5',
  'iris.title': 'IRIS™ Intelligence',
  'iris.subtitle': 'Organizational Intelligence Platform',
  'iris.radar': 'Organizational Radar',
  'iris.score_trend': 'Score Trend',
  'iris.predictive_models': 'Predictive Models',
  'iris.recent_signals': 'Recent Risk Signals',
  'iris.quick_actions': 'Quick Actions',
  'iris.start_scan': 'Start New Scan',
  'iris.view_reports': 'View Reports',
  'iris.benchmark': 'Benchmark',
  'iris.no_alerts': 'No active alerts',
  'iris.no_signals': 'No risk signals detected',
  'iris.no_trend': 'Insufficient data for trend',
  'iris.no_predictions': 'Run predictions to see risk models',
  'iris.no_radar': 'Complete an IRIS Scan to see your organizational radar',
  'iris.score': 'Overall Score',
  'iris.confidence': 'Confidence',
  'iris.active_alerts': 'Active Alerts',
  'iris.ten_dimensions': '10 Dimensions',
  'signals.title': 'Risk Signals',
  'signals.subtitle': 'Detected organizational risk signals',
  'signals.all': 'All',
  'signals.confidence': 'confidence',
  'signals.acknowledge': 'Acknowledge',
  'signals.no_signals': 'No risk signals detected',
  'severity.critical': 'Critical',
  'severity.high': 'High',
  'severity.medium': 'Medium',
  'severity.low': 'Low',
  'severity.info': 'Info',
  'alerts.title': 'IRIS Alerts',
  'alerts.subtitle': 'Organizational monitoring alerts',
  'alerts.no_alerts': 'No active alerts',
  'alerts.dismiss': 'Dismiss',
  'scan.title': 'IRIS Scan',
  'scan.subtitle': 'Organizational Intelligence Scan',
  'scan.start': 'Start New Scan',
  'scan.complete_title': 'Scan Completed',
  'scan.complete_desc': 'Your organizational scan has been completed successfully.',
  'scan.new_scan': 'New Scan',
  'scan.view_dashboard': 'View Dashboard',
  'scan.initializing': 'Initializing...',
  'scan.no_scans': 'No active scans',
  'scan.strongly_disagree': 'Strongly Disagree',
  'scan.disagree': 'Disagree',
  'scan.neutral': 'Neutral',
  'scan.agree': 'Agree',
  'scan.strongly_agree': 'Strongly Agree',
  'scan.depth': 'Depth',
  'scan.all_answered': 'You have answered all questions.',
  'scan.complete': 'Complete Scan',
  'monitor.title': 'IRIS Monitor',
  'monitor.subtitle': 'Continuous organizational health monitoring',
  'monitor.run_weekly': 'Run Weekly',
  'monitor.run_monthly': 'Run Monthly',
  'monitor.run_quarterly': 'Run Quarterly',
  'monitor.running': 'Running...',
  'monitor.frequency': 'Frequency',
  'monitor.status': 'Status',
  'monitor.last_run': 'Last run',
  'monitor.signals': 'Signals',
  'monitor.alerts': 'Alerts',
  'predict.title': 'IRIS Predict',
  'predict.subtitle': 'Predictive organizational risk models',
  'predict.run': 'Run Predictions',
  'predict.running': 'Running...',
  'predict.model': 'Model',
  'predict.probability': 'Probability',
  'predict.horizon': 'horizon',
  'predict.no_predictions': 'Run predictions to see results',
  'predict.causal_factors': 'Causal Factors',
  'predict.recommendations': 'Recommendations',
  'reports.title': 'IRIS Reports',
  'reports.subtitle': 'Organizational intelligence reports',
  'reports.generate': 'Generate',
  'reports.generating': 'Generating...',
  'reports.type': 'Type',
  'reports.status': 'Status',
  'reports.date': 'Date',
  'reports.no_reports': 'No reports generated',
  'benchmark.title': 'Benchmark',
  'benchmark.subtitle': 'Industry organizational comparison',
  'benchmark.your_position': 'Your Position',
  'benchmark.dimension_compare': 'Dimension Comparison',
  'benchmark.filter': 'Filter by Industry',
  'benchmark.compare_btn': 'Compare',
  'benchmark.of': 'of',
  'benchmark.organizations': 'organizations',
  'benchmark.percentile': 'Percentile',
  'benchmark.your_score': 'Your Score',
  'benchmark.no_data': 'No benchmark data',
  'benchmark.no_peers': 'No peer data to compare',
  'benchmark.comparing': 'Comparing with',
  'benchmark.peer_count': 'peers',
  'benchmark.industry_avg': 'Industry average',
  'benchmark.you_are': 'You are',
  'benchmark.your_org': 'Your Org.',
  'benchmark.peer_avg': 'Peer Avg.',
  'admin.title': 'SUPER ADMIN Panel',
  'admin.subtitle': 'IRIS Enterprise global system management',
  'admin.overview': 'Overview',
  'admin.organizations': 'Organizations',
  'admin.users_tab': 'Users',
  'admin.invitations': 'Invitations',
  'admin.licenses': 'Licenses',
  'admin.system': 'System',
  'admin.orgs_stat': 'Organizations',
  'admin.users_stat': 'Users',
  'admin.scans_stat': 'Scans',
  'admin.scores_stat': 'Scores',
  'admin.signals_stat': 'Signals',
  'admin.alerts_stat': 'Alerts',
  'admin.predictions_stat': 'Predictions',
  'admin.reports_stat': 'Reports',
  'admin.avg_score': 'Avg. Score',
  'admin.table_name': 'Name',
  'admin.table_plan': 'Plan',
  'admin.table_users': 'Users',
  'admin.table_scans': 'Scans',
  'admin.table_created': 'Created',
  'admin.table_email': 'Email',
  'admin.table_role': 'Role',
  'admin.table_active': 'Active',
  'admin.table_org': 'Org.',
  'admin.table_status': 'Status',
  'admin.table_expires': 'Expires',
  'admin.create_invitation': 'Create Invitation',
  'admin.email': 'Email',
  'admin.role': 'Role',
  'admin.member_role': 'Member',
  'admin.admin_role': 'Admin',
  'admin.super_admin_role': 'Super Admin',
  'admin.send': 'Send',
  'admin.sent_invitations': 'Sent Invitations',
  'admin.assign_license': 'Assign License',
  'admin.org_id': 'Org. ID',
  'admin.plan': 'Plan',
  'admin.plan_starter': 'Starter',
  'admin.plan_professional': 'Professional',
  'admin.plan_enterprise': 'Enterprise',
  'admin.plan_enterprise_plus': 'Enterprise Plus',
  'admin.assign': 'Assign',
  'admin.system_health': 'System Health',
  'admin.status_label': 'Status',
  'admin.database_label': 'Database',
  'admin.version_label': 'Version',
  'admin.uptime_label': 'Uptime',
  'admin.seed_questions': 'Seed Questions',
  'admin.none': 'None',
  'yes': 'Yes',
  'no': 'No',
};

export default dict;
