const dict: Record<string, string> = {
  'sidebar.iris': 'IRIS™ Platform',
  'sidebar.legacy': 'Legacy',
  'sidebar.intelligence': 'IRIS Intelligence',
  'sidebar.scan': 'IRIS Scan',
  'sidebar.alerts': 'IRIS Alerts',
  'sidebar.signals': 'Risk Signals',
  'sidebar.monitor': 'IRIS Monitor',
  'sidebar.predict': 'IRIS Predict',
  'sidebar.benchmark': 'Benchmark',
  'sidebar.reports': 'Reports',
  'sidebar.dashboard': 'Dashboard',
  'sidebar.assessments': 'Evaluaciones',
  'sidebar.forecast': 'Pronóstico',
  'sidebar.compliance': 'Compliance',
  'sidebar.compliance_center': 'Compliance Center',
  'sidebar.gdpr': 'GDPR',
  'sidebar.iso27001': 'ISO 27001',
  'sidebar.privacy': 'Privacidad',
  'sidebar.anomalies': 'Anomalías',
  'sidebar.api_keys': 'API Keys',
  'sidebar.webhooks': 'Webhooks',
  'sidebar.planning': 'Planificación',
  'sidebar.simulation': 'Simulación',
  'sidebar.ai_analyst': 'AI Analyst',
  'sidebar.billing': 'Facturación',
  'sidebar.sso': 'SSO',
  'sidebar.users': 'Usuarios',
  'sidebar.audit': 'Auditoría',
  'sidebar.zero_trust': 'Zero Trust',
  'sidebar.settings': 'Configuración',
  'sidebar.logout': 'Cerrar sesión',
  'sidebar.loading': 'Cargando...',
  'sidebar.enterprise_v5': 'Enterprise v5',
  'iris.title': 'IRIS™ Intelligence',
  'iris.subtitle': 'Plataforma de Inteligencia Organizacional',
  'iris.radar': 'Radar Organizacional',
  'iris.score_trend': 'Tendencia de Puntaje',
  'iris.predictive_models': 'Modelos Predictivos',
  'iris.recent_signals': 'Señales de Riesgo Recientes',
  'iris.quick_actions': 'Acciones Rápidas',
  'iris.start_scan': 'Iniciar Nuevo Scan',
  'iris.view_reports': 'Ver Reportes',
  'iris.benchmark': 'Benchmark',
  'iris.no_alerts': 'Sin alertas activas',
  'iris.no_signals': 'Sin señales de riesgo detectadas',
  'iris.no_trend': 'Datos insuficientes para tendencia',
  'iris.no_predictions': 'Ejecuta predicciones para ver modelos de riesgo',
  'iris.no_radar': 'Completa un IRIS Scan para ver tu radar organizacional',
  'iris.score': 'Puntaje Integral',
  'iris.confidence': 'Confianza',
  'iris.active_alerts': 'Alertas Activas',
  'iris.ten_dimensions': '10 Dimensiones',
  'signals.title': 'Risk Signals',
  'signals.subtitle': 'Señales de riesgo organizacional detectadas',
  'signals.all': 'Todas',
  'signals.confidence': 'confianza',
  'signals.acknowledge': 'Reconocer',
  'signals.no_signals': 'No se detectaron señales de riesgo',
  'severity.critical': 'Crítica',
  'severity.high': 'Alta',
  'severity.medium': 'Media',
  'severity.low': 'Baja',
  'severity.info': 'Info',
  'alerts.title': 'IRIS Alerts',
  'alerts.subtitle': 'Alertas de monitoreo organizacional',
  'alerts.no_alerts': 'Sin alertas activas',
  'alerts.dismiss': 'Descartar',
  'scan.title': 'IRIS Scan',
  'scan.subtitle': 'Escaneo de Inteligencia Organizacional',
  'scan.start': 'Iniciar Nuevo Scan',
  'scan.complete_title': 'Scan Completado',
  'scan.complete_desc': 'Tu escaneo organizacional ha sido completado exitosamente.',
  'scan.new_scan': 'Nuevo Scan',
  'scan.view_dashboard': 'Ver Dashboard',
  'scan.initializing': 'Inicializando...',
  'scan.no_scans': 'Sin escaneos activos',
  'scan.strongly_disagree': 'Muy en desacuerdo',
  'scan.disagree': 'En desacuerdo',
  'scan.neutral': 'Neutral',
  'scan.agree': 'De acuerdo',
  'scan.strongly_agree': 'Muy de acuerdo',
  'scan.depth': 'Profundidad',
  'scan.all_answered': 'Has respondido todas las preguntas.',
  'scan.complete': 'Completar Scan',
  'monitor.title': 'IRIS Monitor',
  'monitor.subtitle': 'Monitoreo continuo de salud organizacional',
  'monitor.run_weekly': 'Ejecutar Semanal',
  'monitor.run_monthly': 'Ejecutar Mensual',
  'monitor.run_quarterly': 'Ejecutar Trimestral',
  'monitor.running': 'Ejecutando...',
  'monitor.frequency': 'Frecuencia',
  'monitor.status': 'Estado',
  'monitor.last_run': 'Última ejecución',
  'monitor.signals': 'Señales',
  'monitor.alerts': 'Alertas',
  'predict.title': 'IRIS Predict',
  'predict.subtitle': 'Modelos predictivos de riesgo organizacional',
  'predict.run': 'Ejecutar Predicciones',
  'predict.running': 'Ejecutando...',
  'predict.model': 'Modelo',
  'predict.probability': 'Probabilidad',
  'predict.horizon': 'horizonte',
  'predict.no_predictions': 'Ejecuta predicciones para ver resultados',
  'predict.causal_factors': 'Factores Causales',
  'predict.recommendations': 'Recomendaciones',
  'reports.title': 'IRIS Reports',
  'reports.subtitle': 'Reportes de inteligencia organizacional',
  'reports.generate': 'Generar',
  'reports.generating': 'Generando...',
  'reports.type': 'Tipo',
  'reports.status': 'Estado',
  'reports.date': 'Fecha',
  'reports.no_reports': 'Sin reportes generados',
  'benchmark.title': 'Benchmark',
  'benchmark.subtitle': 'Comparativa organizacional por industria',
  'benchmark.your_position': 'Tu Posición',
  'benchmark.dimension_compare': 'Comparativa por Dimensiones',
  'benchmark.filter': 'Filtrar por Industria',
  'benchmark.compare_btn': 'Comparar',
  'benchmark.of': 'de',
  'benchmark.organizations': 'organizaciones',
  'benchmark.percentile': 'Percentil',
  'benchmark.your_score': 'Tu Puntaje',
  'benchmark.no_data': 'Sin datos de benchmark',
  'benchmark.no_peers': 'Sin datos de pares para comparar',
  'benchmark.comparing': 'Comparando con',
  'benchmark.peer_count': 'pares',
  'benchmark.industry_avg': 'Promedio industria',
  'benchmark.you_are': 'Estás en',
  'benchmark.your_org': 'Tu Org.',
  'benchmark.peer_avg': 'Promedio Pares',
  'admin.title': 'Panel SUPER ADMIN',
  'admin.subtitle': 'Gestión global del sistema IRIS Enterprise',
  'admin.overview': 'Resumen',
  'admin.organizations': 'Organizaciones',
  'admin.users_tab': 'Usuarios',
  'admin.invitations': 'Invitaciones',
  'admin.licenses': 'Licencias',
  'admin.system': 'Sistema',
  'admin.orgs_stat': 'Organizaciones',
  'admin.users_stat': 'Usuarios',
  'admin.scans_stat': 'Scans',
  'admin.scores_stat': 'Scores',
  'admin.signals_stat': 'Señales',
  'admin.alerts_stat': 'Alertas',
  'admin.predictions_stat': 'Predicciones',
  'admin.reports_stat': 'Reportes',
  'admin.avg_score': 'Score Promedio',
  'admin.table_name': 'Nombre',
  'admin.table_plan': 'Plan',
  'admin.table_users': 'Usuarios',
  'admin.table_scans': 'Scans',
  'admin.table_created': 'Creado',
  'admin.table_email': 'Email',
  'admin.table_role': 'Rol',
  'admin.table_active': 'Activo',
  'admin.table_org': 'Org.',
  'admin.table_status': 'Estado',
  'admin.table_expires': 'Expira',
  'admin.create_invitation': 'Crear Invitación',
  'admin.email': 'Email',
  'admin.role': 'Rol',
  'admin.member_role': 'Miembro',
  'admin.admin_role': 'Admin',
  'admin.super_admin_role': 'Super Admin',
  'admin.send': 'Enviar',
  'admin.sent_invitations': 'Invitaciones Enviadas',
  'admin.assign_license': 'Asignar Licencia',
  'admin.org_id': 'Org. ID',
  'admin.plan': 'Plan',
  'admin.plan_starter': 'Starter',
  'admin.plan_professional': 'Professional',
  'admin.plan_enterprise': 'Enterprise',
  'admin.plan_enterprise_plus': 'Enterprise Plus',
  'admin.assign': 'Asignar',
  'admin.system_health': 'Salud del Sistema',
  'admin.status_label': 'Estado',
  'admin.database_label': 'Base de Datos',
  'admin.version_label': 'Versión',
  'admin.uptime_label': 'Actividad',
  'admin.seed_questions': 'Sembrar Preguntas',
  'admin.none': 'Ninguno',
  'yes': 'Sí',
  'no': 'No',
};

export default dict;
